<a href="https://www.kaggle.com/code/beyzadurduu/pandas?scriptVersionId=354992097" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/competitions/house-prices-advanced-regression-techniques/sample_submission.csv
/kaggle/input/competitions/house-prices-advanced-regression-techniques/data_description.txt
/kaggle/input/competitions/house-prices-advanced-regression-techniques/train.csv
/kaggle/input/competitions/house-prices-advanced-regression-techniques/test.csv

In [2]:
data=pd.read_csv("/kaggle/input/competitions/house-prices-advanced-regression-techniques/train.csv")

In [3]:
YearBuilt=data.YearBuilt

In [4]:
YearBuilt>50

0       True
1       True
2       True
3       True
4       True
        ...
1455    True
1456    True
1457    True
1458    True
1459    True
Name: YearBuilt, Length: 1460, dtype: bool

In [5]:
data.YearBuilt[YearBuilt>2000].sum

<bound method Series.sum of 0       2003
2       2001
6       2004
11      2005
13      2006
        ...
1444    2004
1451    2008
1452    2005
1453    2006
1454    2004
Name: YearBuilt, Length: 364, dtype: int64>

In [6]:
student_data=[
    [19,204],
    [39,204],
    [49,230],
    [669,20],
    [14,30],
]

In [7]:
student=pd.DataFrame(student_data,columns=["age","point"])

In [8]:
student

   age  point
0   19    204
1   39    204
2   49    230
3  669     20
4   14     30

In [9]:
dic={
    'name':['Beyza',"Ayşe","Fatma"],
    'age':[10,20,30]
}
studentAge=pd.DataFrame(dic)
studentAge=studentAge.set_index('name')

In [10]:
studentAge

       age
name
Beyza   10
Ayşe    20
Fatma   30

In [11]:
data.shape

(1460, 81)

In [12]:
data.dtypes=='int64'

Id                True
MSSubClass        True
MSZoning         False
LotFrontage      False
LotArea           True
                 ...
MoSold            True
YrSold            True
SaleType         False
SaleCondition    False
SalePrice         True
Length: 81, dtype: bool

In [13]:
data.index

RangeIndex(start=0, stop=1460, step=1)

In [14]:
data.values[0:2]

array([[1, 60, 'RL', 65.0, 8450, 'Pave', nan, 'Reg', 'Lvl', 'AllPub',
        'Inside', 'Gtl', 'CollgCr', 'Norm', 'Norm', '1Fam', '2Story', 7,
        5, 2003, 2003, 'Gable', 'CompShg', 'VinylSd', 'VinylSd',
        'BrkFace', 196.0, 'Gd', 'TA', 'PConc', 'Gd', 'TA', 'No', 'GLQ',
        706, 'Unf', 0, 150, 856, 'GasA', 'Ex', 'Y', 'SBrkr', 856, 854, 0,
        1710, 1, 0, 2, 1, 3, 1, 'Gd', 8, 'Typ', 0, nan, 'Attchd', 2003.0,
        'RFn', 2, 548, 'TA', 'TA', 'Y', 0, 61, 0, 0, 0, 0, nan, nan, nan,
        0, 2, 2008, 'WD', 'Normal', 208500],
       [2, 20, 'RL', 80.0, 9600, 'Pave', nan, 'Reg', 'Lvl', 'AllPub',
        'FR2', 'Gtl', 'Veenker', 'Feedr', 'Norm', '1Fam', '1Story', 6, 8,
        1976, 1976, 'Gable', 'CompShg', 'MetalSd', 'MetalSd', nan, 0.0,
        'TA', 'TA', 'CBlock', 'Gd', 'TA', 'Gd', 'ALQ', 978, 'Unf', 0,
        284, 1262, 'GasA', 'Ex', 'Y', 'SBrkr', 1262, 0, 0, 1262, 0, 1, 2,
        0, 3, 1, 'TA', 6, 'Typ', 1, 'TA', 'Attchd', 1976.0, 'RFn', 2,
        460, 'TA', 'TA', 'Y', 298, 0, 0, 0, 0, 0, nan, nan, nan, 0, 5,
        2007, 'WD', 'Normal', 181500]], dtype=object)

In [15]:
data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [16]:
data.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [17]:
data.duplicated()
#yinelenen satır

0       False
1       False
2       False
3       False
4       False
        ...
1455    False
1456    False
1457    False
1458    False
1459    False
Length: 1460, dtype: bool

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [19]:
cat_colums=data.select_dtypes(include=['object']).columns
num_data=pd.get_dummies(data,columns=cat_colums,drop_first=True)

In [20]:
num_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Columns: 246 entries, Id to SaleCondition_Partial
dtypes: bool(208), float64(3), int64(35)
memory usage: 730.1 KB

In [21]:
num_data.sum()

Id                        1066530.0
MSSubClass                  83070.0
LotFrontage                 84130.0
LotArea                  15354569.0
OverallQual                  8905.0
                            ...
SaleCondition_AdjLand           4.0
SaleCondition_Alloca           12.0
SaleCondition_Family           20.0
SaleCondition_Normal         1198.0
SaleCondition_Partial         125.0
Length: 246, dtype: float64

In [22]:
num_data.sum(axis=1)

0       231096.0
1       205011.0
2       249189.0
3       163529.0
4       280645.0
          ...
1455    198270.0
1456    240957.0
1457    294904.0
1458    166384.0
1459    173063.0
Length: 1460, dtype: object

In [23]:
num_data.mean()

Id                         730.500000
MSSubClass                  56.897260
LotFrontage                 70.049958
LotArea                  10516.828082
OverallQual                  6.099315
                             ...
SaleCondition_AdjLand        0.002740
SaleCondition_Alloca         0.008219
SaleCondition_Family         0.013699
SaleCondition_Normal         0.820548
SaleCondition_Partial        0.085616
Length: 246, dtype: float64

In [24]:
num_data.max()

Id                         1460
MSSubClass                  190
LotFrontage               313.0
LotArea                  215245
OverallQual                  10
                          ...
SaleCondition_AdjLand      True
SaleCondition_Alloca       True
SaleCondition_Family       True
SaleCondition_Normal       True
SaleCondition_Partial      True
Length: 246, dtype: object

In [25]:
num_data.min()

Id                           1
MSSubClass                  20
LotFrontage               21.0
LotArea                   1300
OverallQual                  1
                         ...
SaleCondition_AdjLand    False
SaleCondition_Alloca     False
SaleCondition_Family     False
SaleCondition_Normal     False
SaleCondition_Partial    False
Length: 246, dtype: object

In [26]:
num_data['YearBuilt'].var() #verinin ortalamadan uzaklığı

912.2154126019891

In [27]:
num_data.std() #verinin ortalamadan uzaklığı

Id                        421.610009
MSSubClass                 42.300571
LotFrontage                24.284752
LotArea                  9981.264932
OverallQual                 1.382997
                            ...
SaleCondition_AdjLand       0.052289
SaleCondition_Alloca        0.090317
SaleCondition_Family        0.116277
SaleCondition_Normal        0.383862
SaleCondition_Partial       0.279893
Length: 246, dtype: float64

In [28]:
num_data[["SaleCondition_Family","LotArea"]] #slice

      SaleCondition_Family  LotArea
0                    False     8450
1                    False     9600
2                    False    11250
3                    False     9550
4                    False    14260
...                    ...      ...
1455                 False     7917
1456                 False    13175
1457                 False     9042
1458                 False     9717
1459                 False     9937

[1460 rows x 2 columns]

In [29]:
num_data.iloc[0:11:5]

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,False,False,False,False,True,False,False,False,True,False
5,6,50,85.0,14115,5,5,1993,1995,0.0,732,...,False,False,False,False,True,False,False,False,True,False
10,11,20,70.0,11200,5,5,1965,1965,0.0,906,...,False,False,False,False,True,False,False,False,True,False

In [30]:
num_data.iloc[[0,11,5]]

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,False,False,False,False,True,False,False,False,True,False
11,12,60,85.0,11924,9,5,2005,2006,286.0,998,...,False,False,True,False,False,False,False,False,False,True
5,6,50,85.0,14115,5,5,1993,1995,0.0,732,...,False,False,False,False,True,False,False,False,True,False

In [31]:
num_data.iloc[0:3,0:3]

   Id  MSSubClass  LotFrontage
0   1          60         65.0
1   2          20         80.0
2   3          60         68.0

In [32]:
Yapilar_2000=num_data[num_data['YearBuilt']==2000]

In [33]:
y=Yapilar_2000[['Id','YearBuilt','LotFrontage']]

In [34]:
y

        Id  YearBuilt  LotFrontage
4        5       2000         84.0
111    112       2000          NaN
131    132       2000          NaN
180    181       2000          NaN
370    371       2000          NaN
379    380       2000         60.0
474    475       2000         41.0
541    542       2000          NaN
573    574       2000         76.0
610    611       2000          NaN
623    624       2000          NaN
665    666       2000        106.0
742    743       2000         65.0
746    747       2000          NaN
975    976       2000          NaN
1108  1109       2000          NaN
1167  1168       2000         58.0
1203  1204       2000         75.0
1288  1289       2000         40.0
1354  1355       2000          NaN
1358  1359       2000          NaN
1365  1366       2000          NaN
1390  1391       2000         70.0
1433  1434       2000         93.0

In [35]:
y.shape

(24, 3)

In [36]:
y

        Id  YearBuilt  LotFrontage
4        5       2000         84.0
111    112       2000          NaN
131    132       2000          NaN
180    181       2000          NaN
370    371       2000          NaN
379    380       2000         60.0
474    475       2000         41.0
541    542       2000          NaN
573    574       2000         76.0
610    611       2000          NaN
623    624       2000          NaN
665    666       2000        106.0
742    743       2000         65.0
746    747       2000          NaN
975    976       2000          NaN
1108  1109       2000          NaN
1167  1168       2000         58.0
1203  1204       2000         75.0
1288  1289       2000         40.0
1354  1355       2000          NaN
1358  1359       2000          NaN
1365  1366       2000          NaN
1390  1391       2000         70.0
1433  1434       2000         93.0

In [37]:
A=y['LotFrontage']!='NaN'
B=y['YearBuilt']!=1990
y[A&B].shape[0]

24

In [38]:
num_data

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,False,False,False,False,True,False,False,False,True,False
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,False,False,False,False,True,False,False,False,True,False
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,False,False,False,False,True,False,False,False,True,False
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,False,False,False,False,True,False,False,False,False,False
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,False,False,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,False,False,False,False,True,False,False,False,True,False
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,False,False,False,False,True,False,False,False,True,False
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,False,False,False,False,True,False,False,False,True,False
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,False,False,False,False,True,False,False,False,True,False
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,False,False,False,False,True,False,False,False,True,False

In [39]:
num_data['OverallQual']==7

0        True
1       False
2        True
3        True
4       False
        ...
1455    False
1456    False
1457     True
1458    False
1459    False
Name: OverallQual, Length: 1460, dtype: bool

In [40]:
num_data.shape[0]

1460

In [41]:
num_data=num_data.dropna()

In [42]:
num_data.shape[0]

1121